jwt:
  secret: asjkdhakfkasfkaldj
  expiration: 3600000000
  header: Authentication

spring:
  jpa:
    properties:
      event:
        merge:
          entity_copy_observer: allow
      hibernate:
        enable-lazy_load_no_trans: true
      show-sql: true

  datasource:
    username: root
    password: wpwniubi
    url: jdbc:mysql://weiweiwi.top:3306/final-experiment?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    ##Druid数据源配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

server:
  port: 443
  ssl:
    key-store: classpath:3936230_www.weiweiwi.top.pfx
    key-store-password: 6jjoLiJa
    keyStoreType: PKCS12